server:
  port: 1990
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: aigou-config-server:1990.com
    prefer-ip-address: true
spring:
  #profiles:
    #active: native #读取本地配置
  application:
    name: AIGOU-CONFIG-SERVER
  cloud:
    config:
      server:
        #native:
          #search-locations: E:/program/github/aigou-config #本地配置所在的目录
        git:
          uri: https://github.com/fanjunjian124/fenggou-config.git
          username: fanjunjian124
          password: 780136954Ff