server:
  port: 8010
spring:
  application:
    name: fenggou-plat
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: fenggou-plat-8010.com #为当前服务器添加实例的标识
    prefer-ip-address: true